version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
  awseks: circleci/aws-eks@1.0.3

jobs:
  Make_Lint:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Update & install Dependencies
          command: |
            apt-get update
            echo "|||||-----||||||"
            apt-get install tidy -y
            apt-get install wget -y
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64
            chmod +x hadolint
            mv hadolint /bin/hadolint
      - run:
          name: Lint HTML
          command: |
            tidy -q -e *.html
      - run:
          name: Hadolint Dockerfile
          command: |
            hadolint -v
            hadolint --ignore DL3006 Docckerfile
  Dockerize:
    machine: true
    steps:
      - checkout
      - run:
          name: docker logout
          command: |
           docker logout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run: 
          name: Build Image 
          command: |
            docker build -t mohamedatef96/devops-capstone-udacity .
      - run: 
          name: Push Image to DockerHub 
          command: |
            docker push mohamedatef96/devops-capstone-udacity
    
  Apply_Kubectl_Service:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update Kubeconfig
          command: |
            aws eks --region us-west-2 update-kubeconfig --name Udacity-Capstone-master-DevOps

      - run:
          name: Start Blue Service 
          command: |
            kubectl apply -f ./blue-controller.json        
      - run:
          name: Start Green Service 
          command: |       
            kubectl apply -f ./green-controller.json
      - run:
          name: Redirect to Blue 
          command: |       
            kubectl apply -f ./Blue-Service.json
  Apply_Green_service:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update Kubeconfig
          command: |
            aws eks --region us-west-2 update-kubeconfig --name Udacity-Capstone-master-DevOps
      - run:
          name: Redirect to Green
          command: |
            kubectl apply -f ./Green-Service.json
workflows:
  default:
    jobs:
      - Make_Lint
      - Dockerize:
          requires: [Make_Lint]
      - Apply_Kubectl_Service:
          requires: [Dockerize]
      - Approve_Green:
          type: approval
          requires: [Apply_Kubectl_Service]
      - Apply_Green_service:
          requires: [Approve_Green]